# Almost Tuned
mnist_trainer:
  n_timesteps: !!float 2e5
  policy: 'MlpPolicy'
  learning_rate: !!float 2.5e-4
  batch_size: 512
  buffer_size: 100000
  learning_starts: 0
  gamma: 0.99
  target_update_interval: 1250
  train_freq: 16
  gradient_steps: 4
  exploration_fraction: 0.06
  exploration_final_eps: 0.11