mnist_trainer:
  n_timesteps: 20000
  policy: 'MlpPolicy'
  gamma: 0.98
  buffer_size: 200000
  learning_starts: 1000
  noise_type: 'normal'
  noise_std: 0.1
  gradient_steps: -1
  n_episodes_rollout: 1
  learning_rate: !!float 1e-3
  policy_kwargs: "dict(net_arch=[400, 300])"